updating test

diff --git a/tests/inputs b/tests/inputs
--- a/tests/inputs
+++ b/tests/inputs
@@ -1,54 +1,15 @@
-echo hello world
-ls -l -a
-echo "hello world"
-echo 'single quotes'
-echo "mixed 'quotes'"
-echo 'nested "quotes" inside'
-echo hello\ world
-echo "escaped space: \"hello world\""
-echo 'escaped single quote: '\''hello'\'''
-ls -l | grep minishell
-cat file.txt > output.txt
-cat < input.txt | grep "pattern" > output.txt
-echo $HOME
-echo "$USER's home is $HOME"
-ls -l; echo "done"; pwd
-sleep 5 &
-ls -l & echo "background process"
-(echo hello; ls)
-echo "unterminated string
-echo 'another unterminated string
-echo "" | cat -e
-echo "a    b" | tr -s ' '
-echo "tab	separated" | tr '\t' ' '
 && && &&
 || || ||
 | | | |
 && || &&
 || && ||
 | && |
-ls && echo "hello"
-ls |& grep foo
-echo "hello" && ls
-ls && echo "test"
-ls | wc -l
-echo "hello" || ls
-ls || || echo "test"
-ls && && echo "test"
-ls | | wc -l
 && ls
-|| echo "test"
 | grep foo
 ls |
-echo "hello" &&
-cat file ||
 ls && | wc
 echo "hello" || && ls
 grep foo | || cat
-mkdir test | && rm -rf test
-ls & & echo "test"
-echo "hello" | | wc
-cat file | | grep foo
 ls & & echo "test"
 echo "hello" | | wc
 cat file | | grep foo
@@ -58,3 +19,41 @@ cat file | | grep foo
 ls && && echo "hello"
 ||
 |
+&& ls
+|| echo "test"
+| grep foo
+ls &&
+echo "hi" ||
+cat file |
+ls || || echo "test"
+ls && && echo "test"
+ls | | wc -l
+ls && | wc
+echo "hi" || && ls
+grep foo | || cat
+ls & & echo "test"
+ls | | wc
+echo "hello" | | wc
+ls >
+echo "test" <
+ls > | wc
+echo "hi" &&; ls
+ls |; echo "done"
+echo "hello && ls
+echo 'hello ||
+ls && (echo "hello"
+ls | (echo foo
+ls &&  && echo "hello"
+ls ||  || echo "test"
+ls |  | wc
+&&
+||
+|
+echo "hello" &&  
+ls &&# echo "hello"
+echo "hello" &&* ls
+ls && @ wc -l
+echo hello | && ls
+ls || | echo "fail"
+cat file && || echo "done"
+echo "test" | && | wc -l
